"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _movies_card from './movies-card.bones.json'
import _booking_history from './booking-history.bones.json'
import _watch_history from './watch-history.bones.json'

registerBones({
  "movies-card": _movies_card,
  "booking-history": _booking_history,
  "watch-history": _watch_history,
})
